const db = require('../db');
const axios = require('axios');
const UploadedTranscriptProvider = require('../services/meetingSources/UploadedTranscriptProvider');

// URL for the Python ML service
const ML_SERVICE_URL = process.env.ML_SERVICE_URL || 'http://localhost:8000';

exports.analyzeMeeting = async (req, res) => {
    const { title, transcript } = req.body;

    if (!transcript) {
        return res.status(400).json({ error: "Please provide a meeting transcript." });
    }
    if (!title) {
        return res.status(400).json({ error: "Please provide a meeting title." });
    }

    try {
        // 1. Setup Transcript Provider
        const provider = new UploadedTranscriptProvider(transcript);
        const text = await provider.getTranscript();

        // 2. Call ML Service
        let mlResponse;
        try {
            mlResponse = await axios.post(`${ML_SERVICE_URL}/analyze`, { transcript: text }, { timeout: 30000 });
        } catch (mlError) {
            console.error("ML Service Error:", mlError.message);
            return res.status(503).json({ error: "ML Service is unavailable. Please try again later." });
        }

        const data = mlResponse.data;

        // 3. Save to Database
        // Start transaction
        const client = await db.pool.connect();
        try {
            await client.query('BEGIN');

            // Insert meeting
            const meetingRes = await client.query(
                'INSERT INTO meetings (title, transcript, summary) VALUES ($1, $2, $3) RETURNING id',
                [title, text, "Summary generated by MeetMind NLP"]
            );
            const meetingId = meetingRes.rows[0].id;

            // Insert Participants
            for (const p of data.participants) {
                await client.query(
                    'INSERT INTO participants (meeting_id, name) VALUES ($1, $2)',
                    [meetingId, p]
                );
            }

            // Insert Action Items
            for (const item of data.actionItems) {
                await client.query(
                    'INSERT INTO action_items (meeting_id, person, task, deadline, confidence) VALUES ($1, $2, $3, $4, $5)',
                    [meetingId, item.person, item.task, item.deadline, item.confidence]
                );
            }

            // Insert Decisions
            for (const item of data.decisions) {
                await client.query(
                    'INSERT INTO decisions (meeting_id, decision, confidence) VALUES ($1, $2, $3)',
                    [meetingId, item.decision, item.confidence]
                );
            }

            // Insert Deadlines
            for (const item of data.deadlines) {
                await client.query(
                    'INSERT INTO deadlines (meeting_id, description, date, confidence) VALUES ($1, $2, $3, $4)',
                    [meetingId, item.description, item.date, item.confidence]
                );
            }

            // Insert Key Topics
            for (const item of data.keyTopics) {
                await client.query(
                    'INSERT INTO key_topics (meeting_id, topic, confidence) VALUES ($1, $2, $3)',
                    [meetingId, item.topic, item.confidence]
                );
            }

            await client.query('COMMIT');
            
            res.status(201).json({ 
                meetingId, 
                message: "Meeting analyzed and saved successfully.",
                data 
            });

        } catch (dbError) {
            await client.query('ROLLBACK');
            throw dbError;
        } finally {
            client.release();
        }

    } catch (error) {
        console.error("Analysis Error:", error);
        res.status(500).json({ error: "An error occurred during analysis." });
    }
};

exports.getMeetings = async (req, res) => {
    try {
        const page   = Math.max(1, parseInt(req.query.page)  || 1);
        const limit  = Math.min(100, parseInt(req.query.limit) || 20);
        const offset = (page - 1) * limit;

        const [result, countResult] = await Promise.all([
            db.query(
                'SELECT id, title, created_at FROM meetings ORDER BY created_at DESC LIMIT $1 OFFSET $2',
                [limit, offset]
            ),
            db.query('SELECT COUNT(*) FROM meetings')
        ]);

        const total = parseInt(countResult.rows[0].count);
        res.json({
            meetings: result.rows,
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit)
        });
    } catch (error) {
        res.status(500).json({ error: 'Failed to fetch meetings' });
    }
};

exports.getMeetingById = async (req, res) => {
    const { id } = req.params;
    try {
        const meetingRes = await db.query('SELECT * FROM meetings WHERE id = $1', [id]);
        if (meetingRes.rows.length === 0) {
            return res.status(404).json({ error: "Meeting not found" });
        }
        
        const meeting = meetingRes.rows[0];

        const [participants, actionItems, decisions, deadlines, keyTopics] = await Promise.all([
            db.query('SELECT * FROM participants WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM action_items WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM decisions WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM deadlines WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM key_topics WHERE meeting_id = $1', [id])
        ]);

        res.json({
            ...meeting,
            participants: participants.rows,
            actionItems: actionItems.rows,
            decisions: decisions.rows,
            deadlines: deadlines.rows,
            keyTopics: keyTopics.rows
        });

    } catch (error) {
        res.status(500).json({ error: "Failed to fetch meeting details" });
    }
};

exports.deleteMeeting = async (req, res) => {
    const { id } = req.params;
    try {
        // Cascade delete will handle related tables
        const result = await db.query('DELETE FROM meetings WHERE id = $1 RETURNING id', [id]);
        if (result.rows.length === 0) {
            return res.status(404).json({ error: "Meeting not found" });
        }
        res.json({ message: "Meeting deleted successfully" });
    } catch (error) {
        res.status(500).json({ error: "Failed to delete meeting" });
    }
};

exports.getDashboardStats = async (req, res) => {
    try {
        const [meetings, actionItems, pendingActions, decisions] = await Promise.all([
            db.query('SELECT COUNT(*) FROM meetings'),
            db.query('SELECT COUNT(*) FROM action_items'),
            db.query("SELECT COUNT(*) FROM action_items WHERE status = 'Pending'"),
            db.query('SELECT COUNT(*) FROM decisions')
        ]);
        
        res.json({
            totalMeetings: parseInt(meetings.rows[0].count),
            totalActionItems: parseInt(actionItems.rows[0].count),
            pendingActionItems: parseInt(pendingActions.rows[0].count),
            totalDecisions: parseInt(decisions.rows[0].count),
        });
    } catch (error) {
        res.status(500).json({ error: "Failed to fetch dashboard stats" });
    }
};

exports.updateActionItemStatus = async (req, res) => {
    const { id } = req.params;
    const { status } = req.body;
    
    try {
        const result = await db.query(
            'UPDATE action_items SET status = $1 WHERE id = $2 RETURNING *',
            [status, id]
        );
        if (result.rows.length === 0) {
            return res.status(404).json({ error: "Action item not found" });
        }
        res.json(result.rows[0]);
    } catch (error) {
        res.status(500).json({ error: "Failed to update action item" });
    }
}

exports.summarizeMeeting = async (req, res) => {
    const { id } = req.params;
    try {
        // Fetch all extracted meeting data from DB
        const [meetingRes, actionRes, decisionRes, deadlineRes, participantRes, topicRes] = await Promise.all([
            db.query('SELECT * FROM meetings WHERE id = $1', [id]),
            db.query('SELECT * FROM action_items WHERE meeting_id = $1 ORDER BY confidence DESC', [id]),
            db.query('SELECT * FROM decisions WHERE meeting_id = $1 ORDER BY confidence DESC', [id]),
            db.query('SELECT * FROM deadlines WHERE meeting_id = $1 ORDER BY confidence DESC', [id]),
            db.query('SELECT * FROM participants WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM key_topics WHERE meeting_id = $1', [id]),
        ]);

        if (meetingRes.rows.length === 0) {
            return res.status(404).json({ error: 'Meeting not found' });
        }

        const meeting   = meetingRes.rows[0];
        const actions   = actionRes.rows;
        const decisions = decisionRes.rows;
        const deadlines = deadlineRes.rows;
        const people    = participantRes.rows;
        const topics    = topicRes.rows;

        // ── Build structured, human-readable summary ──────────────────────────
        const date = new Date(meeting.created_at).toLocaleDateString('en-US', {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
        });
        const nameList = people.map(p => p.name).join(', ') || 'multiple participants';
        const lines = [];

        // 1. Overview sentence
        lines.push(
            `This meeting was held on ${date} with ${people.length || 'several'} participant${people.length !== 1 ? 's' : ''} (${nameList}).`
        );

        // 2. Topics
        if (topics.length) {
            lines.push(`Topics discussed included ${topics.map(t => t.topic).join(', ')}.`);
        }

        // 3. Decisions (narrative)
        if (decisions.length) {
            lines.push('');
            lines.push('Key decisions made:');
            decisions.forEach(d => {
                // Strip "We decided to" / speaker prefixes for cleaner output
                const text = d.decision
                    .replace(/^(we\s+)?(decided|agreed|resolved|confirmed)\s+(to\s+)?/i, '')
                    .replace(/^[A-Za-z]+:\s*/,'')
                    .trim();
                const capitalised = text.charAt(0).toUpperCase() + text.slice(1);
                lines.push(`• ${capitalised}`);
            });
        }

        // 4. Action items (narrative)
        if (actions.length) {
            lines.push('');
            lines.push('Action items assigned:');
            actions.forEach(a => {
                const who = a.person && a.person !== 'Unknown' ? a.person : 'Team';
                const deadline = a.deadline ? ` — due ${a.deadline}` : '';
                // Strip leading speaker name from task text
                const task = a.task.replace(/^[A-Za-z]+:\s*/, '').trim();
                lines.push(`• ${who}: ${task}${deadline}`);
            });
        }

        // 5. Upcoming deadlines
        if (deadlines.length) {
            lines.push('');
            lines.push('Key deadlines:');
            deadlines.forEach(d => {
                const desc = d.description.replace(/^[A-Za-z]+:\s*/, '').trim();
                lines.push(`• ${d.date ? d.date + ': ' : ''}${desc}`);
            });
        }

        // 6. Closing
        const totalItems = actions.length + decisions.length + deadlines.length;
        if (totalItems > 0) {
            lines.push('');
            lines.push(
                `Overall, ${totalItems} item${totalItems !== 1 ? 's' : ''} were captured — ` +
                `${actions.length} action item${actions.length !== 1 ? 's' : ''}, ` +
                `${decisions.length} decision${decisions.length !== 1 ? 's' : ''}, and ` +
                `${deadlines.length} deadline${deadlines.length !== 1 ? 's' : ''}.`
            );
        }

        const summary = lines.join('\n');

        // Cache in DB so next load is instant
        await db.query('UPDATE meetings SET summary = $1 WHERE id = $2', [summary, id]);

        res.json({ summary });
    } catch (err) {
        console.error('summarizeMeeting error:', err);
        res.status(500).json({ error: 'Failed to generate summary' });
    }
};

// ── Global action items (all meetings) ────────────────────────────────────────
exports.getAllActionItems = async (req, res) => {
    try {
        const { status } = req.query;
        const params = [];
        let where = '';
        if (status) { where = 'WHERE ai.status = $1'; params.push(status); }
        const result = await db.query(
            `SELECT ai.*, m.title as meeting_title, m.created_at as meeting_date
             FROM action_items ai
             JOIN meetings m ON m.id = ai.meeting_id
             ${where}
             ORDER BY ai.created_at DESC
             LIMIT 200`,
            params
        );
        res.json(result.rows);
    } catch (err) {
        res.status(500).json({ error: 'Failed to fetch action items' });
    }
};

// ── Upcoming deadlines (all meetings) ─────────────────────────────────────────
exports.getAllDeadlines = async (req, res) => {
    try {
        const result = await db.query(
            `SELECT d.*, m.title as meeting_title, m.id as meeting_id, m.created_at as meeting_date
             FROM deadlines d
             JOIN meetings m ON m.id = d.meeting_id
             ORDER BY d.created_at DESC
             LIMIT 200`
        );
        res.json(result.rows);
    } catch (err) {
        res.status(500).json({ error: 'Failed to fetch deadlines' });
    }
};
