const db = require('../db');
const axios = require('axios');
const UploadedTranscriptProvider = require('../services/meetingSources/UploadedTranscriptProvider');

// URL for the Python ML service
const ML_SERVICE_URL = process.env.ML_SERVICE_URL || 'http://localhost:8000';

exports.analyzeMeeting = async (req, res) => {
    const { title, transcript } = req.body;

    if (!transcript) {
        return res.status(400).json({ error: "Please provide a meeting transcript." });
    }
    if (!title) {
        return res.status(400).json({ error: "Please provide a meeting title." });
    }

    try {
        // 1. Setup Transcript Provider
        const provider = new UploadedTranscriptProvider(transcript);
        const text = await provider.getTranscript();

        // 2. Call ML Service
        let mlResponse;
        try {
            mlResponse = await axios.post(`${ML_SERVICE_URL}/analyze`, { transcript: text }, { timeout: 30000 });
        } catch (mlError) {
            console.error("ML Service Error:", mlError.message);
            return res.status(503).json({ error: "ML Service is unavailable. Please try again later." });
        }

        const data = mlResponse.data;

        // 3. Save to Database
        // Start transaction
        const client = await db.pool.connect();
        try {
            await client.query('BEGIN');

            // Insert meeting
            const meetingRes = await client.query(
                'INSERT INTO meetings (title, transcript, summary) VALUES ($1, $2, $3) RETURNING id',
                [title, text, "Summary generated by MeetMind NLP"]
            );
            const meetingId = meetingRes.rows[0].id;

            // Insert Participants
            for (const p of data.participants) {
                await client.query(
                    'INSERT INTO participants (meeting_id, name) VALUES ($1, $2)',
                    [meetingId, p]
                );
            }

            // Insert Action Items
            for (const item of data.actionItems) {
                await client.query(
                    'INSERT INTO action_items (meeting_id, person, task, deadline, confidence) VALUES ($1, $2, $3, $4, $5)',
                    [meetingId, item.person, item.task, item.deadline, item.confidence]
                );
            }

            // Insert Decisions
            for (const item of data.decisions) {
                await client.query(
                    'INSERT INTO decisions (meeting_id, decision, confidence) VALUES ($1, $2, $3)',
                    [meetingId, item.decision, item.confidence]
                );
            }

            // Insert Deadlines
            for (const item of data.deadlines) {
                await client.query(
                    'INSERT INTO deadlines (meeting_id, description, date, confidence) VALUES ($1, $2, $3, $4)',
                    [meetingId, item.description, item.date, item.confidence]
                );
            }

            // Insert Key Topics
            for (const item of data.keyTopics) {
                await client.query(
                    'INSERT INTO key_topics (meeting_id, topic, confidence) VALUES ($1, $2, $3)',
                    [meetingId, item.topic, item.confidence]
                );
            }

            await client.query('COMMIT');
            
            res.status(201).json({ 
                meetingId, 
                message: "Meeting analyzed and saved successfully.",
                data 
            });

        } catch (dbError) {
            await client.query('ROLLBACK');
            throw dbError;
        } finally {
            client.release();
        }

    } catch (error) {
        console.error("Analysis Error:", error);
        res.status(500).json({ error: "An error occurred during analysis." });
    }
};

exports.getMeetings = async (req, res) => {
    try {
        const page   = Math.max(1, parseInt(req.query.page)  || 1);
        const limit  = Math.min(100, parseInt(req.query.limit) || 20);
        const offset = (page - 1) * limit;

        const [result, countResult] = await Promise.all([
            db.query(
                'SELECT id, title, created_at FROM meetings ORDER BY created_at DESC LIMIT $1 OFFSET $2',
                [limit, offset]
            ),
            db.query('SELECT COUNT(*) FROM meetings')
        ]);

        const total = parseInt(countResult.rows[0].count);
        res.json({
            meetings: result.rows,
            total,
            page,
            limit,
            totalPages: Math.ceil(total / limit)
        });
    } catch (error) {
        res.status(500).json({ error: 'Failed to fetch meetings' });
    }
};

exports.getMeetingById = async (req, res) => {
    const { id } = req.params;
    try {
        const meetingRes = await db.query('SELECT * FROM meetings WHERE id = $1', [id]);
        if (meetingRes.rows.length === 0) {
            return res.status(404).json({ error: "Meeting not found" });
        }
        
        const meeting = meetingRes.rows[0];

        const [participants, actionItems, decisions, deadlines, keyTopics] = await Promise.all([
            db.query('SELECT * FROM participants WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM action_items WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM decisions WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM deadlines WHERE meeting_id = $1', [id]),
            db.query('SELECT * FROM key_topics WHERE meeting_id = $1', [id])
        ]);

        res.json({
            ...meeting,
            participants: participants.rows,
            actionItems: actionItems.rows,
            decisions: decisions.rows,
            deadlines: deadlines.rows,
            keyTopics: keyTopics.rows
        });

    } catch (error) {
        res.status(500).json({ error: "Failed to fetch meeting details" });
    }
};

exports.deleteMeeting = async (req, res) => {
    const { id } = req.params;
    try {
        // Cascade delete will handle related tables
        const result = await db.query('DELETE FROM meetings WHERE id = $1 RETURNING id', [id]);
        if (result.rows.length === 0) {
            return res.status(404).json({ error: "Meeting not found" });
        }
        res.json({ message: "Meeting deleted successfully" });
    } catch (error) {
        res.status(500).json({ error: "Failed to delete meeting" });
    }
};

exports.getDashboardStats = async (req, res) => {
    try {
        const [meetings, actionItems, pendingActions, decisions] = await Promise.all([
            db.query('SELECT COUNT(*) FROM meetings'),
            db.query('SELECT COUNT(*) FROM action_items'),
            db.query("SELECT COUNT(*) FROM action_items WHERE status = 'Pending'"),
            db.query('SELECT COUNT(*) FROM decisions')
        ]);
        
        res.json({
            totalMeetings: parseInt(meetings.rows[0].count),
            totalActionItems: parseInt(actionItems.rows[0].count),
            pendingActionItems: parseInt(pendingActions.rows[0].count),
            totalDecisions: parseInt(decisions.rows[0].count),
        });
    } catch (error) {
        res.status(500).json({ error: "Failed to fetch dashboard stats" });
    }
};

exports.updateActionItemStatus = async (req, res) => {
    const { id } = req.params;
    const { status } = req.body;
    
    try {
        const result = await db.query(
            'UPDATE action_items SET status = $1 WHERE id = $2 RETURNING *',
            [status, id]
        );
        if (result.rows.length === 0) {
            return res.status(404).json({ error: "Action item not found" });
        }
        res.json(result.rows[0]);
    } catch (error) {
        res.status(500).json({ error: "Failed to update action item" });
    }
}

exports.summarizeMeeting = async (req, res) => {
    const { id } = req.params;
    try {
        const meetingRes = await db.query('SELECT transcript FROM meetings WHERE id = $1', [id]);
        if (meetingRes.rows.length === 0) {
            return res.status(404).json({ error: 'Meeting not found' });
        }
        const { transcript } = meetingRes.rows[0];
        let mlResponse;
        try {
            mlResponse = await axios.post(`${ML_SERVICE_URL}/summarize`, { transcript }, { timeout: 30000 });
        } catch (mlErr) {
            console.error('Summarize ML error:', mlErr.message);
            return res.status(503).json({ error: 'ML Service unavailable. Is it running on port 8000?' });
        }
        const summary = mlResponse.data.summary;
        // Cache the summary back into the meetings table
        await db.query('UPDATE meetings SET summary = $1 WHERE id = $2', [summary, id]);
        res.json({ summary });
    } catch (err) {
        console.error('summarizeMeeting error:', err);
        res.status(500).json({ error: 'Failed to generate summary' });
    }
};
